FROM node:18-alpine

WORKDIR /app/frontend

COPY ./package*.json ./

RUN npm install && \
    npm install react-scripts@3.4.1 -g 

COPY ./ ./

CMD npm run build && npm install -g serve && serve -s build