version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    volumes:
      - ./frontend:/app/frontend

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev

  beat:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev