FROM python:3.11-alpine

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app/backend
COPY requirements.txt /app/backend

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

COPY ./ ./

CMD python manage.py wait_for_db && \
    python manage.py makemigrations && \
    python manage.py migrate && \
    python manage.py collectstatic --no-input && \
    python manage.py runserver 0.0.0.0:8000