FROM python:3.10-alpine

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Environment variables for Firefox
ENV MOZ_HEADLESS=1
ENV MOZ_DISABLE_GPU_PROCESS=1
ENV MOZ_DISABLE_CONTENT_SANDBOX=1
ENV MOZ_DISABLE_GMP_SANDBOX=1

# Setup working directory
WORKDIR /app/backend
COPY requirements.txt /app/backend

# Install required packages for Firefox and geckodriver, as well as additional dependencies
RUN apk add --no-cache firefox wget ttf-freefont dbus xvfb

# Download and install geckodriver
RUN wget https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz && \
    tar -zxf geckodriver-v0.33.0-linux64.tar.gz -C /usr/local/bin && \
    chmod +x /usr/local/bin/geckodriver && \
    rm geckodriver-v0.33.0-linux64.tar.gz

# Install Python dependencies
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Copy the rest of the code
COPY ./ ./

CMD python manage.py wait_for_db && \
    python manage.py makemigrations && \
    python manage.py migrate && \
    python manage.py collectstatic --no-input && \
    python manage.py runserver 0.0.0.0:8000
